# Generated by Django 5.2.1 on 2025-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='graph_type',
            field=models.CharField(choices=[('parabola', 'Парабола (y = x²)'), ('exponent', 'Экспонента (y = e^x)')], default='parabola', max_length=20),
        ),
    ]
